enum actionTypes {
  CHANGE_BANNER = "home/discovery/CHANGE_BANNER",
  CHANGE_RECOMMEND_MV_LIST = "home/discovery/CHANGE_RECOMMEND_MV_LIST",
  CHANGE_RECOMMEND_SONG_LIST = "home/discovery/CHANGE_RECOMMEND_SONG_LIST",

  CHANGE_RECOMMEND_SONGLIST_LIST = "home/discovery/CHANGE_RECOMMEND_SONGLIST_LIST",

  CHANGE_RECOMMEND_DJ_LIST = "home/discovery/CHANGE_RECOMMEND_DJ_LIST",

  CHANGE_ENTER_LOADING= 'home/discovery/CHANGE_ENTER_LOADING',
}

export default actionTypes;